before_script:
  - git submodule sync --recursive
  - git submodule update --init --recursive

stages:
  - lint
  - build

lint:
   stage: lint
   script:
     # Check for tabs
     - cd ssc &&
       if grep --recursive --include={*.cpp,*.c,*.hpp,*.h,*.md,*.yml,*.cmake.*.xml,*.html,*.in,*.txt}
               --exclude-dir={eigen,f2c,gcovr,geographiclib,gmock,google-test,gtest,websocketpp,yaml-cpp,geometry,integrate,interpolation} -P "\t" . ;
       then echo "Tabs found in the lines shown above."; false;
       else echo "Repo passed no-tabs check."; fi &&
       cd ..

build:windows:
   stage: build
   script:
     - docker run --rm -v /etc/group:/etc/group:ro  -v /etc/passwd:/etc/passwd:ro -u $( id -u $USER ):$( id -g $USER ) -v $(pwd):/opt/share -w /opt/share mydockcross/windows-x64
          cmake -Wno-dev
          -G Ninja
          -DCMAKE_INSTALL_PREFIX:PATH=/opt/ssc
          -DIPOPT_ROOT:PATH=/opt/CoinIpopt
          -DBOOST_ROOT:PATH=/opt/boost
          -DBoost_DEBUG=1
          /opt/share/ssc
     - docker run --rm -v /etc/group:/etc/group:ro  -v /etc/passwd:/etc/passwd:ro -u $( id -u $USER ):$( id -g $USER ) -v $(pwd):/opt/share -w /opt/share mydockcross/windows-x64 ninja package
     - docker run --rm -v /etc/group:/etc/group:ro  -v /etc/passwd:/etc/passwd:ro -u $( id -u $USER ):$( id -g $USER ) -v $(pwd):/opt/share -w /opt/share mydockcross/windows-x64 wine ./run_all_tests

build:debian:
   stage: build
   script:
     - docker build -f Dockerfile -t ssc .
     - docker run --rm -v /etc/group:/etc/group:ro  -v /etc/passwd:/etc/passwd:ro -u $( id -u $USER ):$( id -g $USER ) -v $(pwd):/opt/share -w /opt/share ssc
          cmake -Wno-dev
          -G Ninja
          -DCMAKE_INSTALL_PREFIX:PATH=/opt/ssc
          -DIPOPT_ROOT:PATH=/opt/CoinIpopt
          -DBOOST_ROOT:PATH=/opt/boost
          /opt/share/ssc
     - docker run --rm -v /etc/group:/etc/group:ro  -v /etc/passwd:/etc/passwd:ro -u $( id -u $USER ):$( id -g $USER ) -v $(pwd):/opt/share -w /opt/share ssc ninja package
     - docker run --rm -v /etc/group:/etc/group:ro  -v /etc/passwd:/etc/passwd:ro -u $( id -u $USER ):$( id -g $USER ) -v $(pwd):/opt/share -w /opt/share ssc ./run_all_tests
   artifacts:
     paths:
     - ssc.deb

