before_script:
  - git submodule sync --recursive
  - git submodule update --init --recursive

build:
   stage: build
   script:
     - RUNNING=$(docker inspect --format="{{ .State.Running }}" cont_ssc 2> /dev/null) && if [ $? -eq 0 ]; then echo "Deleting cont_ssc"; docker rm cont_ssc; fi
     - docker build -f ssc/Dockerfile -t ssc .
     # - docker run --name cont_ssc ssc
     # - docker stop cont_ssc
     # - docker rm cont_ssc
