before_script:
  - git submodule sync --recursive
  - git submodule update --init --recursive

build:
   stage: build
   script:
     # Check for tabs
     - cd ssc &&
       if grep --recursive --include={*.cpp,*.c,*.hpp,*.h,*.md,*.yml,*.cmake.*.xml,*.html,*.in,*.txt}
               --exclude-dir={eigen,f2c,gcovr,geographiclib,gmock,google-test,gtest,websocketpp,yaml-cpp,geometry,integrate,interpolation} -P "\t" . ;
       then echo "Tabs found in the lines shown above."; false;
       else echo "Repo passed no-tabs check."; fi &&
       cd ..
     - docker run --rm -v $(pwd):/opt/share -w /opt/share ssc
          cmake -Wno-dev
          -G Ninja
          -DCMAKE_INSTALL_PREFIX:PATH=/opt/ssc
          -DIPOPT_ROOT:PATH=/opt/CoinIpopt
          -DBOOST_ROOT:PATH=/opt/boost
          /opt/share/ssc
     - docker run --rm -v $(pwd):/opt/share -w /opt/share ssc ninja package
     - docker run --rm -v $(pwd):/opt/share -w /opt/share ssc ./run_all_tests
   artifacts:
     paths:
     - ssc.deb
