before_script:
  - git submodule sync --recursive
  - git submodule update --init --recursive

build:
   stage: build
   script:
     - cd ssc &&
       if grep --recursive --include={*.cpp,*.c,*.hpp,*.h,*.md,*.yml,*.cmake.*.xml,*.html,*.in,*.txt}
               --exclude-dir={eigen,f2c,gcovr,geographiclib,gmock,google-test,gtest,websocketpp,yaml-cpp} -P "\t" . ;
       then echo "Tabs found in the lines shown above."; false;
       else echo "Repo passed no-tabs check."; fi &&
       cd ..
     # - RUNNING=$(docker inspect --format="{{ .State.Running }}" cont_ssc 2> /dev/null) && if [ $? -eq 0 ]; then echo "Deleting cont_ssc"; docker rm cont_ssc; fi
     - docker build -f ssc/Dockerfile -t ssc .
     # - docker run --name cont_ssc ssc
     # - docker stop cont_ssc
     # - docker rm cont_ssc
