before_script:
  - git submodule sync --recursive
  - git submodule update --init --recursive

stages:
  - lint
  - build

lint:
   stage: lint
   script:
     - make lint

build:windows:
   stage: build
   script:
     - make windows_posixthreads
     - mv ssc/build_win/ssc.zip .
   artifacts:
     paths:
     - ssc.zip

build debian 10 with gcc 8:
   stage: build
   script:
     - make debian_10_release_gcc_8
     - mv ssc/build_deb10/ssc.deb .
   artifacts:
     paths:
     - ssc.deb

