sudo: false
dist: trusty

language: c++

git:
  submodules: false

services:
  - docker

env:
  global:
  - DOCKER_USERNAME=gjacquenot
  - secure: "R6iNMz54usAq4qGX+8k8YfGyJ0oQpGf7ReqHCZStCzDiUJ+daYZgaNE4iXWkslMun8uG1USTBJAYKUuZWLtE0Z8k0qog8rL8ayXV5nJXdZ9XJSKVakGioIGoL28EwDe9HNuZ5v1xfwjl9z/1EO93bRoYifqqaE8QDdUqgMyWivAdanPVTM3Ro5tAWADnwS5ITYDh4iE8hQwLZDa8GeVCdJhJT4zmnmTa2a2oBZ12uBdWJ1V40Et0O54LSEt2vgtuuafp889dqlhXTzlvQ3rmn2IdoyzxCNBTzL75MTxAvF/8S6YGa91OsjKeJ3qgAJwHtzm1pvSTmzbAeTLAYqf2k0jtffAQS211K33KQnGS5d3DIIGoQYpzBT96mfRWbdOYIjGgbmHlplBfESbZpa30QQAvf7UP7BM4TEntmD+unYu+NdDvl8HpqXSL7sxHJYbC22xCrfG+A6qSQZJspi6Hc/hg3zDoDrqu4f06T0+1vr67Tl9/PVBhzU/ajM9wIA1z9vtSOg3FsMfbEtRMsoE+Lui2pdvTKYfPJqSZOe0GCIblr+tr/wFuvnYQZrjz8SmBDmQVI9q33XUihKronnA9UlDoKxLM1AVoADh/x+MEUjCaVOCCK3vuf28qrftLSh3X0QHkYy2SG7RRhDZk7r6osr4tVekAVJx6DihLkPMbPZM="

matrix:
  include:
    - name: "Deb 8 release"
      env:
        - BUILD_TYPE=Release
        - BUILD_DIR=build_deb8
        - CPACK_GENERATOR=DEB DOCKER_IMAGE=gjacquenot/ssc_build
        - BOOST_ROOT=/opt/boost
    - name: "Deb 8 coverage"
      env:
        - BUILD_TYPE=Coverage
        - BUILD_DIR=build_deb8
        - CPACK_GENERATOR=DEB
        - DOCKER_IMAGE=gjacquenot/ssc_build
        - BOOST_ROOT=/opt/boost
    - name: "Deb 9 release"
      env:
        - BUILD_TYPE=Release
        - BUILD_DIR=build_deb9
        - CPACK_GENERATOR=DEB
        - DOCKER_IMAGE=gjacquenot/ssc_build_debian9_gcc8
        - BOOST_ROOT=/opt/boost
    - name: "Win Release cross compilation"
      env:
        - BUILD_TYPE=Release
        - BUILD_DIR=build_win
        - CPACK_GENERATOR=ZIP
        - DOCKER_IMAGE=gjacquenot/ssc_build_win64
        - BOOST_ROOT=/usr/src/mxe/usr/x86_64-w64-mingw32.static

before_install:
  - docker pull $DOCKER_IMAGE || true

script:
  - if [[ $BUILD_TYPE == "Coverage" ]];
    then
    ci_env=`bash <(curl -s https://codecov.io/env)`;
    else
    ci_env=;
    fi
  - docker run $ci_env --rm -u $( id -u $USER ):$( id -g $USER ) -v $(pwd):/opt/share -w /opt/share $DOCKER_IMAGE /bin/bash -c \
       "rm -rf /opt/share/ssc/google-test &&
        cp -rf /opt/googletest /opt/share/ssc/google-test &&
        rm -rf /opt/share/ssc/eigen &&
        cp -rf /opt/eigen /opt/share/ssc/eigen &&
        rm -rf /opt/share/ssc/yaml-cpp &&
        cp -rf /opt/yaml_cpp /opt/share/ssc/yaml-cpp &&
        cp /opt/share/ssc/CMakeLists_yaml_cpp.txt /opt/share/ssc/yaml-cpp/CMakeLists.txt &&
        rm -rf /opt/share/ssc/websocketpp &&
        cp -rf /opt/websocketpp /opt/share/ssc/websocketpp &&
        rm -rf /opt/share/ssc/f2c &&
        cp -rf /opt/libf2c /opt/share/ssc/f2c &&
        cd /opt/share/ssc/f2c &&
        sed 's/typedef long int integer/typedef int integer/g' f2c.h0 > f2c.h &&
        cp signal1.h0 signal1.h &&
        cp sysdep1.h0 sysdep1.h &&
        cd .. &&
        cp CMakeLists_f2c.txt f2c/CMakeLists.txt &&
        rm -rf /opt/share/ssc/geographiclib &&
        cp -rf /opt/geographiclib /opt/share/ssc/geographiclib &&
        cp /opt/share/ssc/CMakeLists_geographiclib.txt /opt/share/ssc/geographiclib/CMakeLists.txt &&
        cd /opt/share/ssc/geographiclib &&
        echo add_library \(Geographic_object OBJECT \\\${SOURCES} \\\${HEADERS}\) >> src/CMakeLists.txt &&
        cd /opt/share/ssc &&
        mkdir -p $BUILD_DIR &&
        cd $BUILD_DIR &&
        if [[ $BUILD_DIR == build_win ]];
        then
        mkdir /opt/share/.wine;
        export WINEPREFIX=/opt/share/.wine;
        wine winecfg;
        fi &&
        cmake -Wno-dev
          -G Ninja
          -DCPACK_GENERATOR=$CPACK_GENERATOR
          -DCMAKE_BUILD_TYPE=$BUILD_TYPE
          -DCMAKE_INSTALL_PREFIX:PATH=/opt/ssc
          -DBOOST_ROOT:PATH=$BOOST_ROOT
          -DBOOST_INCLUDEDIR:PATH=$BOOST_ROOT/include
          -DBoost_INCLUDE_DIR:PATH=$BOOST_ROOT/include
          -DBOOST_LIBRARYDIR:PATH=$BOOST_ROOT/lib
          -DBoost_NO_SYSTEM_PATHS:BOOL=OFF
          -DBoost_LIBRARY_DIR_RELEASE:PATH=$BOOST_ROOT/lib
          -DIPOPT_ROOT:PATH=/opt/CoinIpopt
          -DCOIN_BLAS:PATH=/opt/CoinIpopt/lib/libcoinblas.a
          -DCOIN_LAPACK:PATH=/opt/CoinIpopt/lib/libcoinlapack.a
          -DCOIN_MUMPS:PATH=/opt/CoinIpopt/lib/libcoinmumps.a
          -DCOIN_IPOPT:PATH=/opt/CoinIpopt/lib/libipopt.a
          -DIPOPT_INCLUDE_DIRS:PATH=/opt/CoinIpopt/include/coin
          -DIPOPT_LIB_DYNAMIC=\"gfortran;gcc;quadmath;m\"
          /opt/share/ssc &&
        ninja package &&
        if [[ $BUILD_DIR == build_win ]];
        then
        wine ./run_all_tests --gtest_filter=-WebSocketObserverTest*;
        else
        ./run_all_tests;
        fi &&
        if [[ $BUILD_TYPE == Coverage ]];
        then
        echo Coverage;
        gprof run_all_tests gmon.out > gprof_res.txt;
        bash <(curl -s https://codecov.io/bash);
        fi
        "

after_success:
- |
    echo "TRAVIS_BRANCH  $TRAVIS_BRANCH"
    echo "TRAVIS_TAG     $TRAVIS_TAG"
    echo "BUILD_TYPE     $BUILD_TYPE"
    echo "BUILD_DIR      $BUILD_DIR"
- if [ "$TRAVIS_TAG" ] && [ "$BUILD_TYPE" == "Release" ] && [ "$BUILD_DIR" == "build_deb8" ];
  then
  echo "Pushing ssc docker image to dockerhub";
  docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD;
  cp ssc/$BUILD_DIR/ssc.deb ci/ssc_deb/.;
  cd ci;
  cd ssc_deb;
  docker build --tag gjacquenot/ssc -f Dockerfile .;
  docker push gjacquenot/ssc;
  cd ..;
  cd ..;
  fi
- if [ "$TRAVIS_TAG" ] && [ "$BUILD_TYPE" == "Release" ] && [ "$BUILD_DIR" == "build_deb8" ];
  then
  echo "Fetching generated deb";
  ls -altr ssc/$BUILD_DIR/ssc.deb;
  shasum -a256 ssc/$BUILD_DIR/ssc.deb;
  cp ssc/$BUILD_DIR/ssc.deb ssc_binary_debian8_amd64.deb;
  fi
- if [ "$TRAVIS_TAG" ] && [ "$BUILD_TYPE" == "Release" ] && [ "$BUILD_DIR" == "build_deb9" ];
  then
  echo "Fetching generated deb";
  ls -altr ssc/$BUILD_DIR/ssc.deb;
  shasum -a256 ssc/$BUILD_DIR/ssc.deb;
  cp ssc/$BUILD_DIR/ssc.deb ssc_binary_debian9_amd64.deb;
  fi
- if [ "$TRAVIS_TAG" ] && [ "$BUILD_TYPE" == "Release" ] && [ "$BUILD_DIR" == "build_win" ];
  then
  echo "Fetching generated zip";
  ls -altr ssc/build_win/ssc.zip;
  shasum -a256 ssc/build_win/ssc.zip;
  cp ssc/build_win/ssc.zip ssc_binary_windows_64.zip;
  fi

# travis setup releases
# https://docs.travis-ci.com/user/deployment
# https://docs.travis-ci.com/user/deployment#conditional-releases-with-on
before_deploy:
- ls -altr ssc_binary_*;
# - ls -altr ssc_binary_debian8_amd64.deb;
# - ls -altr ssc_binary_windows_64.zip;
deploy:
  provider: releases
  api_key:
    secure: OHuqTi6NfB19u4PA2WwdNp4aDrHI4nXo8j4jgtCkpD3cX1UnXkDX86sDpktHWbtqbWkMYKQlNvRdRWcQUMIcvtJPPxF89msuDAPwGsBiXVAifsFSESD4CZzv0LQ0Cjcn0BLU5VDobMfAhbQf7ADH6S1Ie07Bb9Bfo0lsvjrkpDB8tw0oG5sILQ1n4SR1ZMSczRCHqRR449keMi0bcj6sexTlbgtJENTQa7va4ro3V7n/96/eGUu4zj7j2/ppP+lMYG1VeoGJX3AmuC7n/d1+VNG4l11ItAluRmwTnBAcN/D9zSwMKoBbVDmAFw+Eur++P/yow/Dsn9UOy8YGhqmB/Wtb9FlGkNHb2zg5pig5sUjtrMKHc7HWcl/u3AGZ9FIfQLwzwzFyHVbW6xsjiIEn3e797elJsEKh5Ds6y8ZwNtbResrSoSWebgh+q0ujMFlg4nOKnv9SeOXtB4IWVtjXafdZhpAlpy1YjHAbrw5Q+PcBWra2k5sDk/1RslxIJvEQy133ZGxuxCSrjfHGnp0rG+jvBQrzKwmmr7/gjCxTLcbYIB400MYGeP7CXoEvTI6Mhb58GPKfaoSCx7CxyG2kR2c7RAV/tz2l+hoPbov8sKWpQswAx6Yye7IDgDvhPf2CI72eFqLnEyIQOwF+kvKo8bjkV9vrvlw9fh0uMe2woTw=
  skip_cleanup: true
  file_glob: true
  file:
    - ssc_binary_*
  #file:
  #  - ssc_binary_debian8_amd64.deb
  #  - ssc_binary_windows_64.zip
  on:
    tags: true
    repo: Gjacquenot/ssc
    branch: master
    condition: $BUILD_TYPE = Release
