PLATFORM = win32
TRGT = w32

CPP = gcc
OBJ_EXT = .o
OBJ_DIR = bin/$(PLATFORM)
DYN_EXT = .dll
EXE_EXT =
LIB_EXT = .lib

SHARED_LIB = -D_JNI_IMPLEMENTATION_ -Wl,--kill-at

IPOPT_DIR = ../../Ipopt

LAPACK = lapack$(DYN_EXT)
LAPACK_DIR = source/lapack
LAPACK_LIB = source/lapack/*.o ../libf2c/libf2c.a 
#bin/win32/lapack.dll
#lib
#$(LAPACK)

CFLAGS = -D NDEBUG

include Makefile.mk



include Makefile.inc
